"""Init ExtremeValue

Revision ID: d13fb9b31d32
Revises: 292900da74c5
Create Date: 2024-03-29 22:48:49.903218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13fb9b31d32'
down_revision: Union[str, None] = '292900da74c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extreme_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_full_power', sa.Float(), nullable=True),
    sa.Column('max_full_power', sa.Float(), nullable=True),
    sa.Column('min_active_power', sa.Float(), nullable=True),
    sa.Column('max_active_power', sa.Float(), nullable=True),
    sa.Column('min_reactive_power', sa.Float(), nullable=True),
    sa.Column('max_reactive_power', sa.Float(), nullable=True),
    sa.Column('min_voltage', sa.Float(), nullable=True),
    sa.Column('max_voltage', sa.Float(), nullable=True),
    sa.Column('min_amperage', sa.Float(), nullable=True),
    sa.Column('max_amperage', sa.Float(), nullable=True),
    sa.Column('min_power_factor', sa.Float(), nullable=True),
    sa.Column('max_power_factor', sa.Float(), nullable=True),
    sa.Column('add_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extreme_value')
    # ### end Alembic commands ###
